apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipelines-vote-api
  name: pipelines-vote-api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      nodePort: 40000
  selector:
    app: pipelines-vote-api
